---
title: "PCA"
author: "PeterBergmann"
date: "10 September 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analytics Vidhya PCA website.

This is a replication of the PCA example on the Analytich Vidhya website.

```{r}

# ser working directory to the source file location
install.packages('rstudioapi')
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# check the working directory
getwd()

#load data
train <- read.csv("../Data/train_Big.csv")
#summary(train)

test <- read.csv("../Data/test_Big.csv")

#check column names
colnames(test)

#check data content
head(train)


#add a column
#we add the column
#because we do not have the test sales data
test$Item_Outlet_Sales <- 1

#check the data content
head(test)

#combine the data set
combi <- rbind(train, test)

#impute missing values with median
combi$Item_Weight[is.na(combi$Item_Weight)] <- median(combi$Item_Weight, na.rm = TRUE)

#impute 0 with median
combi$Item_Visibility <- ifelse(combi$Item_Visibility == 0, median(combi$Item_Visibility), combi$Item_Visibility)

#find mode and impute
table(combi$Outlet_Size, combi$Outlet_Type)
levels(combi$Outlet_Size)[1] <- "Other"

#remove the dependent and identifier variables
my_data <- subset(combi, select = -c(Item_Outlet_Sales, Item_Identifier, Outlet_Identifier))

#let us check the available variables (predictors) in the data set
colnames(my_data)

#check variable class
str(my_data)

# some of our variables are categorical variables
# let us convert these variables into numeric using hot encoding
# load library
install.packages('dummies')
library(dummies)

#create a dummy data frame
new_my_data <- dummy.data.frame(my_data, names = c("Item_Fat_Content", "Item_Type", "Outler_Establishment_Year", "Outlet_Size", "Outlet_Location_Type", "Outlet_Type"))

#check that we do not have factor variables
str(new_my_data)


#and now we have all the numerical values. Let us divide the data #into test and train
pca.train <- new_my_data[1:nrow(train),]
pca.test <- new_my_data[-(1:nrow(train)),]

# we can now go with PCA


# principal component analysis
prin_comp <- prcomp(pca.train, scale. = T)
names(prin_comp)

#outputs the mean of variables
prin_comp$center

#let us look at first 4 principal components and first 5 rows
prin_comp$rotation[1:5, 1:4]

#let us plot the residual principal components
biplot(prin_comp, scale = 0)

#compute standard deviation of each prinical component
std_dev <- prin_comp$sdev

#compute variance
pr_var <- std_dev^2

#check variance of first 10 components
pr_var[1:10]

# to compute the proportion of variance explained by each component,
# we divide the variance by sum of total variance
prop_varex <- pr_var / sum(pr_var)
prop_varex[1:20]


#scree plot
plot(prop_varex, xlab = "Principal Component", ylab = "Proportion of Variance Explained", type = "b")

#cumulative scree plot
plot(cumsum(prop_varex), xlab = "Principal Component", ylab = "Cumulative Proportion of Variance Explained", type = "b")

#add a training set with principal component
train.data <-data.frame(Item_Outlet_Sales = train$Item_Outlet_Sales, prin_comp$x)

#we are interested in first 30 PCAs
train.data <-train.data[, 1:31]

#run a decision tree
install.packages("rpart")
library(rpart)
rpart.model <- rpart(Item_Outlet_Sales~ ., data = train.data, method = "anova")
rpart.model

#transform test into PCA
test.data <- predict(prin_comp, newdata = pca.test)
test.data <- as.data.frame(test.data)

#select the first 30 components
test.data <- test.data[, 1:30]

#make prediction on test data
rpart.prediction <- predict(rpart.model, test.data)
rpart.prediction

summary

#for fun, check your score of leaderboard
sample <- read.csv("../Data/SampleSubmission_TmnO39y.csv")
final.sub <- data.frame(Item_Identifier = sample$Item_Identifier, Outlet_Identifier = sample$Outlet_Identifier, Item_Outlet_Sales = rpart.prediction)

# can we do th
#run regression
lm.model <- lm(Item_Outlet_Sales ~ .,data = train.data)
lm.model

#residual sum of squares
rss <-c(crossprod(lm.model$residuals))
rss

#mean squared error
mse <-rss / length(lm.model$residuals)
mse

#root mse
rmse <- sqrt(mse)
rmse

#summary
summary.lm(lm.model)

#transform test into PCA
test.data <- predict(prin_comp, newdata = pca.test)
test.data <- as.data.frame(test.data)

#select the first 30 components
test.data <- test.data[, 1:30]

#make prediction on the test data
lm.prediction <- predict(test.data)


```
